repos:
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.33.0
  hooks:
  - id: yamllint
    args: [-c=.yamllint.yaml]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.9.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
